<?php
 /**
 * Iterator Sistemas Web
 *
 * NOTAS SOBRE LICENÇA
 *
 * Este arquivo de código-fonte está em vigência dentro dos termos da EULA.
 * Ao fazer uso deste arquivo em seu produto, automaticamente você está 
 * concordando com os termos do Contrato de Licença de Usuário Final(EULA)
 * propostos pela empresa Iterator Sistemas Web.
 *
 * =================================================================
 *                   MÓDULO DE MOTOR DE IMPOSTOS
 * =================================================================
 * Este produto foi desenvolvido para o Ecommerce Magento de forma a
 * automatizar cálculos de impostos existentes em operações fiscais.
 * Através deste módulo a loja virtual do contratante do serviço
 * passará a conter diversos cálculos envolvendo documentos fiscais
 * em operações de entradas e também de saídas de forma automática.
 * =================================================================
 *
 * @category   Iterator
 * @package    Iterator_MotorImpostos
 * @author     Ricardo Auler Barrientos <contato@iterator.com.br>
 * @copyright  Copyright (c) Iterator Sistemas Web - CNPJ: 19.717.703/0001-63
 * @license    O Produto é protegido por leis de direitos autorais, bem como outras leis de propriedade intelectual.
 */

$_htmlId      = $this->getElement()->getHtmlId();
$_htmlClass   = $this->getElement()->getClass();
$_htmlName    = $this->getElement()->getName();
$_readonly    = $this->getElement()->getReadonly();
$impostoId = Mage::registry('motorimpostos/imposto')->getId();
if($impostoId) {
    $collection = Mage::getResourceModel('motorimpostos/impostouf_collection')->addFieldToFilter('imposto_id', $impostoId);
} else {
    $collection = Mage::getModel('directory/region')->getResourceCollection()->addCountryFilter('BR')->load();
}
$_counter = 0;
?>

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td colspan="10" class="grid estados">
        <table id="attribute-options-table" class="dynamic-grid motorimpostos-interestaduais" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <td colspan="3" align="center" bgcolor="#D7E5EF" style="font-weight:bold;font-size:13px;">Tabela com os impostos interestaduais</td>
                </tr>
            </thead>
            <tbody>
                <tr class="headings">
                    <th style="text-align:center; width:400px;" title="Produto">Estado</th>
                    <th style="text-align:center; width:200px;" title="<?php echo utf8_encode('Alíq. ICMS'); ?>"><?php echo utf8_encode('Alíq. ICMS'); ?></th>
                    <th style="text-align:center; width:200px;" title="IVA/MVA">IVA/MVA</th>
                </tr>
                <?php foreach ($collection as $impostoUf): ?>
                <tr class="option-row motorimpostos-interestaduais-estadorow" id="estado-row-<?php echo $_counter?>">                    
                    <td>
                        <?php
                        if($impostoId) {
                            $region = Mage::getModel('directory/region')->load($impostoUf->getRegionId());
                            $estadoLabel = $region->getDefaultName();
                        } else {
                            $estadoLabel = $impostoUf->getDefaultName();
                        }
                        ?>
                        <label class="widget-option-label" id="estado<?php echo $_counter?>label"><?php echo $estadoLabel ?></label>
                    </td>
                    <input type="hidden" id="region_id<?php echo $_counter?>value" name="<?php echo $_htmlName; ?>[value][option_<?php echo $_counter ?>][region_id]" value="<?php echo $impostoUf->getRegionId() ?>" />
                    <td align="center"><input id="aliquota_icms<?php echo $_counter?>value" name="<?php echo $_htmlName; ?>[value][option_<?php echo $_counter ?>][aliquota_icms]" value="<?php echo $impostoUf->getAliquotaIcms() ?>" class="validate-zero-or-greater input-text" type="text"></td>
                    <td align="center"><input id="mva_original<?php echo $_counter?>value" name="<?php echo $_htmlName; ?>[value][option_<?php echo $_counter ?>][mva_original]" value="<?php echo $impostoUf->getMvaOriginal() ?>" class="validate-zero-or-greater input-text" type="text"></td>
                </tr>
                <?php 
                $_counter++;
                endforeach;
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" align="left" style="font-style:italic;font-size:10px;"><?php echo utf8_encode('* Não é necessário incluir casas decimais, em caso de utilização pode-se optar por ponto(.) ou vírgula(,) que em ambos os casos será formatado automaticamente para a forma correta.') ?></td>
                </tr>
            </tfoot>
        </table>
    </td>
</tr>